################# Application info #################
appName=HammerAnimations-Standalone
appVersion=1.0.39
####################### MISC #######################
# LWJGL
lwjglVersion=3.3.4
lwjglNatives=natives-windows
# Lombok
lombok=1.18.46
# Dependencies
lzvmVersion=1.0.1
tupleVersion=1.2.1
jsonVersion=20251224
jomlVersion=1.10.8
####################################################
