modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/dragon-forge/HammerAnimations/issues"
license="All Rights Reserved"

[[mods]]
modId="hammeranims"
version="${file.jarVersion}"
displayName="HammerAnimations"
updateJSONURL="https://api.modrinth.com/updates/C7cTlgwS/forge_updates.json"
displayURL="https://modrinth.com/mod/C7cTlgwS"
logoFile="logo.png"
credits="Mojang (creation of model & animation standard)"
authors="Zeitheron"
description='''
Library mod for Minecraft: Java Edition. Brings Bedrock model and animation as a compact and easy-to-use API layer with hotswapping.
To perform hot-reload, run "/hammeranims reload"
'''

[[dependencies.hammeranims]]
    modId="forge"
    mandatory=true
    versionRange="[36.1,)"
    ordering="NONE" # NONE/BEFORE/AFTER
    side="BOTH"
[[dependencies.hammeranims]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.hammeranims]]
    modId="hammerlib"
    mandatory=true
    versionRange="[16.5.50,)"
    ordering="NONE"
    side="BOTH"
